# Generated by Django 6.0.2 on 2026-03-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('dry', 'Dry'), ('sugary', 'Sugary'), ('alcohol_free', 'Alcohol free')], max_length=20)),
                ('preparation_time', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('servings', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('ustensils', models.TextField()),
            ],
        ),
    ]
