# Generated by Django 6.0.2 on 2026-03-02 13:34

from django.db import migrations

def seed_cocktails(apps, schema_editor):
    Cocktail = apps.get_model('cocktails', 'Cocktail')

    Cocktail.objects.create(
        name="Mojito",
        category="sugary",
        preparation_time=10,
        ingredients="Mint leaves, lime, sugar, white rum, sparkling water",
        steps="Muddle mint and sugar. Add lime. Add rum. Add ice. Top with sparkling water.",
        servings=1,
        difficulty="easy",
        ustensils="muddler, spoon, glass",
        image="cocktails/mojito.jpg"
    )

    Cocktail.objects.create(
        name="Negroni",
        category="dry",
        preparation_time=3,
        ingredients="Gin, Campari, sweet vermouth",
        steps="Stir ingredients with ice. Strain into glass. Garnish with orange peel.",
        servings=1,
        difficulty="medium",
        ustensils="mixing glass, strainer",
        image="cocktails/negroni.jpg"
    )

    Cocktail.objects.create(
        name="Virgin Mojito",
        category="alcohol_free",
        preparation_time=5,
        ingredients="Mint leaves, lime, sugar, sparkling water",
        steps="Muddle mint and sugar. Add lime. Add ice. Top with sparkling water.",
        servings=1,
        difficulty="easy",
        ustensils="muddler, spoon, glass",
        image="cocktails/virgin_mojito.jpg"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_cocktail_image'),
    ]

    operations = [
        migrations.RunPython(seed_cocktails),
    ]
