name: Dependency Security Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  scan-node:
    name: Scan Node.js dependencies (Express API)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./express

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm install

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth "$SNYK_TOKEN"

      - name: Run Snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=package.json --package-manager=npm

  scan-python:
    name: Scan Python dependencies (Django)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./django
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth "$SNYK_TOKEN"

      - name: Run Snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=requirements.txt --package-manager=pip

  Trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          format: 'table'
          exit-code: '1'
          scan-type: 'fs'
